---
################# nginx ########################

- name: Nginx setup
  shell: |
    sudo systemctl start nginx
    sudo bash -c 'cat <<EOF> /etc/nginx/sites-available/yummy
    server {
        listen 80;
        server_name api2.philophilo.xyz;
        location / {
            proxy_pass http://127.0.0.1:8000/;
            proxy_set_header Host \$host;
            proxy_set_header X-Forwarded-Proto \$scheme;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        }
    }
    EOF'
    sudo rm -rf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default 
    sudo ln -s /etc/nginx/sites-available/yummy /etc/nginx/sites-enabled/

- name: start Nginx
  shell: |
    sudo systemctl restart nginx # restart nginx
    sudo systemctl status nginx
