- hosts: localhost
  connection: local
  become: yes

  vars:
    dir: /home/ubuntu/
    app_dir: /home/ubuntu/yummy_api

  tasks:
    - name: Update source list
      environment:
        LANG: "en_US.UTF-8"
        LC_ALL: "en_US.UTF-8"
        LC_CTYPE: "en_US.UTF-8"
      apt: name={{item}} update_cache=yes state=present
      with_items:
        - python-apt

    - name: add python3.6 external source
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
        update_cache: yes
    
    - name: install python3.6
      apt: 
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
        - python3.6
        - python3-pip
        - python3.6-dev
        - python3-gdbm

    # find a way to copy files
    - name: copy apt_pkg.so
      copy: remote_src=True src=/usr/lib/python3/dist-packages/apt_pkg.cpython-35m-x86_64-linux-gnu.so dest=/usr/lib/python3/dist-packages/apt_pkg.so

    - name: Set python3.5 with lower priority
      alternatives:
        name: python3
        link: /usr/bin/python3
        path: /usr/bin/python3.5
        priority: 1

    - name: Set python3.6 with higher priority
      alternatives:
        name: python3
        link: /usr/bin/python3
        path: /usr/bin/python3.6
        priority: 10

    - name: Install servers
      apt:
        name: "{{ item }}"
      with_items:
        - nginx
        - gunicorn

    - name: install python dependencies
      apt: 
        name: "{{ item }}"
        state: present
      with_items: 
        - build-essential
        - autoconf
        - libtool
        - pkg-config
        - python-opengl
        - python-imaging
        - python-pyrex
        - python-pyside.qtopengl
        - idle-python2.7
        - qt4-dev-tools
        - qt4-designer
        - libqtgui4
        - libqtcore4
        - libqt4-xml
        - libqt4-test
        - libqt4-script
        - libqt4-network
        - libqt4-dbus
        - python-qt4
        - python-qt4-gl
        - libgle3
        - python-dev
        - libssl-dev

    - name: install greenlet and gevent
      shell: |
        easy_install greenlet
        easy_install gevent

    - name: Install virtual environment
      shell: |
        cd ..
        sudo -H pip3 install virtualenv
        virtualenv -p python3 venv
        . venv/bin/activate

    - name: Git clone repo
      git:
        repo: https://github.com/philophilo/yummy_api.git
        dest: "{{ app_dir }}"
