- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Update source list
      environment:
        LANG: "en_US.UTF-8"
        LC_ALL: "en_US.UTF-8"
        LC_CTYPE: "en_US.UTF-8"
      apt: name={{item}} update_cache=yes state=present
      with_items:
        - python-apt

    - name: add python3.6 external source
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
        update_cache: yes
    
    - name: install python3.6
      apt: 
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
        - python3.6
        - python3-pip
        - python3.6-dev
        - python3-gdbm

    # find a way to copy files
    - name: copy apt_pkg.so
      copy: remote_src=True src=/usr/lib/python3/dist-packages/apt_pkg.cpython-35m-x86_64-linux-gnu.so dest=/usr/lib/python3/dist-packages/apt_pkg.so
