---
############### app ######################

- name: Git clone repo
  git:
    repo: https://github.com/philophilo/yummy_api.git
    dest: "{{ app_dir }}"

- name: install pip requirements
  shell: |
    pwd
    . /home/ubuntu/venv/bin/activate
    cd /home/ubuntu/yummy_api
    pip install -r requirements.txt

# database migrations
- name: Database setup
  shell: |
    export DATABASE_URL='postgresql://philophilo:12345678@databasepsql.c4ecouwmxh9c.us-east-2.rds.amazonaws.com:5432/yummy'
    cd /home/ubuntu/yummy_api
    . /home/ubuntu/venv/bin/activate
    python manage.py db init
    python manage.py db migrate
    python manage.py db upgrade
    deactivate
  ignore_errors: yes
