---
#########  essentials ##################

- name: install python essentials
  apt: 
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - python3-pip
    - python3-dev
    - nginx
    - python3-gdbm
    - autoconf
    - libtool
    - pkg-config
    - python-opengl
    - python-imaging
    - python-pyrex
    - python-pyside.qtopengl
    - idle-python2.7
    - qt4-dev-tools
    - qt4-designer
    - libqtgui4
    - libqtcore4
    - libqt4-xml
    - libqt4-test
    - libqt4-script
    - libqt4-network
    - libqt4-dbus
    - python-qt4
    - python-qt4-gl
    - libgle3
    - python-dev
    - libssl-dev

- name: Install virtual environment
  shell: |
    pip3 install virtualenv
    virtualenv -p python3 venv

